common:
  dataset_root: &dataset_root ~/dataset_repos
  batch_size: &batch_size 64

datasets: # Required
  train:
    type: deep_learning.datasets.Cifar10Dataset
    kwargs:
      root: *dataset_root
      train: True
    batch_size: *batch_size

    transforms:
      - type: torchvision.transforms.ToTensor
        turn_on: True

  test:
    type: deep_learning.datasets.Cifar10Dataset
    kwargs:
      root: *dataset_root
      train: False
    batch_size: *batch_size

    transforms:
      - type: torchvision.transforms.ToTensor
        turn_on: True

net: # Required
  input_shapes: [[1, 3, 32, 32],]
  type: deep_learning.models.vgg11_bn
  kwargs:
    num_classes: 10

trainer: # Required
  max_epoch: 128
  print_freq: 100
  test_freq: 4

  optimizer:
    type: torch.optim.SGD
    kwargs:
      lr: 0.01
      momentum: 0.9
      nesterov: True

  lr_scheduler:
    type: torch.optim.lr_scheduler.StepLR
    kwargs:
      step_size: 25000
      gamma: 0.1
